### ISSUE TITLE
Build for Ubuntu

### ISSUE THREAD

**Issue by vahid-dan** [AquaticEcoDynamics/GLM#10]
Hi;

I was wondering if you have the instructions to build GLM for Ubuntu.

Thanks in advance. :-)

Bests,
Vahid

**Comment by matthipsey** [comment]
Hi Vahid

The build scripts are in the AED_Scripts folder. It has instructions and also a build_glm.sh script to manage the compilation.

Cheers
Matt




On 9 Jan 2019, at 1:50 pm, Vahid Daneshmand <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi;

I was wondering if you have the instructions to build GLM for Ubuntu.

Thanks in advance. :-)

Bests,
Vahid

**Comment by vahid-dan** [comment]
Hi Matt;

Thanks for your prompt response. By `AED_Scripts` folder, you mean `AED_Tools` repo?

Thanks,
Vahid

**Comment by matthipsey** [comment]
My apologies, Yes that's correct…!!

On 9 Jan 2019, at 2:05 pm, Vahid Daneshmand <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Matt;

Thanks for your prompt response. By AED_Scripts folder, you mean AED_Tools repo?

Thanks,
Vahid

**Comment by vahid-dan** [comment]
Matt,

I cannot find any instructions for building GLM on Ubuntu and it seems it is not trivial. I guess there are several dependencies missing. Can you kindly provide me with some more details? I'd be grateful.

Thanks,
Vahid

**Comment by vahid-dan** [comment]
Matt,

I got this error at the end of the building process on Ubuntu 16.04 with `GCC-8` and `gfortran-8`:

```
no change to version number in ./glm.rc
no change to version number in ./glm+.rc
debian version 3.0.0beta10
dh_testdir
mkdir -p /home/vd/workspace/GLM/debian/glm/usr/local/bin
(cp /home/vd/workspace/GLM/glm /home/vd/workspace/GLM/debian/glm/usr/local/bin)
dh_install
dh_install: glm+ missing files: glm+
dh_install: missing files, aborting
debian/rules:11: recipe for target 'binary' failed
make: *** [binary] Error 2
```

Does it ring a bell for you?

Thanks,
Vahid

**Comment by vahid-dan** [comment]
Hi;

Any update on this issue?

Thanks in advance. :-)

Bests,
Vahid

**Comment by robertladwig** [comment]
Hi,

I don't really know how relevant this is, but a friend helped me in building GLM on Ubuntu 18.04. using the following: 

sudo apt install git gfortran-8 libnetcdf-dev libgd-dev
mkdir AquaticEcoDynamics
cd AquaticEcoDynamics
 
git clone https://github.com/AquaticEcoDynamics/libplot.git
cd libplot
make
cd ..
 
git clone https://github.com/AquaticEcoDynamics/libaed2.git
cd libaed2
F90=gfortran-8 make
cd ..
 
git clone https://github.com/AquaticEcoDynamics/libutil.git
cd libutil
F90=gfortran-8 make
cd ..
 
git clone https://github.com/AquaticEcoDynamics/GLM.git
cd GLM
FC=gfortran-8 ./build_glm.sh
 
mkdir ~/.local/bin
ln -s $(realpath glm) ~/.local/bin/glm

Afterwards you can run it by using 'glm'
Cheers,
Robert

**Comment by vahid-dan** [comment]
Hi @robertladwig;

Thanks a lot. It worked for me on Ubuntu 16.04, as well.

Bests,
Vahid
