### ISSUE TITLE
New zone structure pointer problem

### ISSUE THREAD

**Issue by matthipsey** [AquaticEcoDynamics/GLM#23]
https://github.com/AquaticEcoDynamics/GLM/blob/7b7826159dce5945b76d99fa05778357373e8367/src/glm_zones.F90#L96

Casper - Been doing some tests with zones and benthic_mode=2 for current version. The new zone-specific sediment layers is giving me a problem with the pointer, referenced at the above line. It seems the first entry (i.e. the first zone) is referenced properly, but zones 2 and 3 have 0 and random, respectively. So in this check I have hard-coded a value to make it work, but can you check the pointer operation here?

**Comment by casper-boon** [comment]
The problem was when you added heatflux to glm_types.F90 Zone structure you forgot to also add it to glm_types.h
