### ISSUE TITLE
GLM 2.4 NS issue

### ISSUE THREAD

**Issue by matthipsey** [AquaticEcoDynamics/GLM#5]
Line 139-144

this was added to allow volume to get updated after the water level dropped below 10cm (MphInc); the height would keep dropping in glm_surface, but the one_layer routine wouldn’t be called to update the volume - therefore below 0.1m the volume held constant but height would go negative)

with this code NS (active layer number) hits only 1, even for 40m deep lake

**Comment by rqthomas** [comment]
@matthipsey @casper-boon status update? Can this be closed?
